### ISSUE TITLE
having error after choosing region

### ISSUE THREAD

**Issue by Ezhavu** [deCodeIt/book-my-show-notification#14]
hi im getting error after choosing the region. can any check and please help me resolve me this. i dont know python just foloowing the steps

> Traceback (most recent call last):
  File "BookMyShow.py", line 340, in <module>
    venues = bms.searchVenue( args.cinema )
  File "BookMyShow.py", line 129, in searchVenue
    venues = self.fetchVenues()
  File "BookMyShow.py", line 126, in fetchVenues
    return BMSVenue.parse_raw( data.stdout )
  File "pydantic\main.py", line 549, in pydantic.main.BaseModel.parse_raw
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for BMSVenue
BookMyShow
  field required (type=value_error.missing)

**Comment by Ezhavu** [comment]
> Traceback (most recent call last):
  File "BookMyShow.py", line 340, in <module>
    venues = bms.searchVenue( args.cinema )
  File "BookMyShow.py", line 129, in searchVenue
    venues = self.fetchVenues()
  File "BookMyShow.py", line 126, in fetchVenues
    return BMSVenue.parse_raw( data.stdout )
  File "pydantic\main.py", line 549, in pydantic.main.BaseModel.parse_raw
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for BMSVenue
BookMyShow
  field required (type=value_error.missing)
